const SETTING_KEYS = {
  CATALOG_FOLDER_FILE_PATH: 'folder_file_path',
  CATALOG_VIDEO_FILE_PATH: 'video_file_path',
  LINKAGE_FILE_PATH: 'linkage_file_path',
  SIGHTING_FILE_PATH: 'sighting_file_path',
  STILL_EXPORT_FILE_PATH: 'still_export_file_path',
  OBSERVER_FILE_PATH: 'observer_file_path',

  THUMBNAIL_DIR_PATH: 'thumbnail_dir_path',
  STILLEXPORT_DIR_PATH: 'stillexport_dir_path',

  BASE_FOLDER_OF_VIDEOS: 'base_folder_of_videos',
  BASE_FOLDER_OF_ORIGINAL_VIDEOS: 'base_folder_of_original_videos',

  BASE_FOLDER_OF_OPTIMIZED_IMAGES: 'base_folder_of_optimized_images',
  BASE_FOLDER_OF_ORIGINAL_IMAGES: 'base_folder_of_original_images',
}

const REQUIRED_SETTINGS = [
  SETTING_KEYS.CATALOG_FOLDER_FILE_PATH,
  SETTING_KEYS.CATALOG_VIDEO_FILE_PATH,
  SETTING_KEYS.LINKAGE_FILE_PATH,
  SETTING_KEYS.SIGHTING_FILE_PATH,
  SETTING_KEYS.OBSERVER_FILE_PATH,
  SETTING_KEYS.STILL_EXPORT_FILE_PATH,
  SETTING_KEYS.BASE_FOLDER_OF_VIDEOS,
  SETTING_KEYS.BASE_FOLDER_OF_ORIGINAL_VIDEOS,
  SETTING_KEYS.BASE_FOLDER_OF_OPTIMIZED_IMAGES,
  SETTING_KEYS.BASE_FOLDER_OF_ORIGINAL_IMAGES,
  SETTING_KEYS.THUMBNAIL_DIR_PATH,
  SETTING_KEYS.STILLEXPORT_DIR_PATH,
]

const SETTING_TYPE_FOR_KEY = {
  [SETTING_KEYS.CATALOG_FOLDER_FILE_PATH]: 'excel',
  [SETTING_KEYS.CATALOG_VIDEO_FILE_PATH]: 'excel',
  [SETTING_KEYS.LINKAGE_FILE_PATH]: 'excel',
  [SETTING_KEYS.SIGHTING_FILE_PATH]: 'excel',
  [SETTING_KEYS.STILL_EXPORT_FILE_PATH]: 'excel',
  [SETTING_KEYS.OBSERVER_FILE_PATH]: 'excel',

  [SETTING_KEYS.THUMBNAIL_DIR_PATH]: 'folder',
  [SETTING_KEYS.STILLEXPORT_DIR_PATH]: 'folder',
  [SETTING_KEYS.BASE_FOLDER_OF_VIDEOS]: 'folder',
  [SETTING_KEYS.BASE_FOLDER_OF_ORIGINAL_VIDEOS]: 'folder',
  [SETTING_KEYS.BASE_FOLDER_OF_OPTIMIZED_IMAGES]: 'folder',
  [SETTING_KEYS.BASE_FOLDER_OF_ORIGINAL_IMAGES]: 'folder',
}

export { REQUIRED_SETTINGS, SETTING_TYPE_FOR_KEY }
export default SETTING_KEYS
